services:
  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"  # Exposes container port 8001 to host port 8001
    restart: always
    environment:
      - RI_ACCEPT_TERMS_AND_CONDITIONS=yes  # Accept EULA automatically
      - RI_APP_PORT=8001
    volumes:
      - redisinsight-data:/db

volumes:
  redis-data:
  redisinsight-data:
