services:
  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - redisinsight-data:/db

volumes:
  redis-data:
  redisinsight-data:
